"""Domain policy: normalisation and fuzzy scoring. Pure, so no database anywhere here.

The numbers asserted below were MEASURED against the live library on 2026-08-19, not
estimated. They are pinned because the threshold depends on them: if a change moves the
typo case below `DEFAULT_FUZZY_THRESHOLD`, real searches start returning nothing and the
only symptom is silence.
"""

from __future__ import annotations

import difflib

import pytest

from zotero_core.domain.services.policy import (
    DEFAULT_FUZZY_THRESHOLD,
    fuzzy_score,
    normalize_title,
    surname_of,
)

TARGET = "Bayesian Learning via Stochastic Gradient Langevin Dynamics"


# --------------------------------------------------------------------------
# normalisation
# --------------------------------------------------------------------------


def test_accents_fold_because_they_are_decoration():
    assert normalize_title("Hébert") == normalize_title("Hebert")


def test_kana_voicing_marks_are_preserved_because_they_are_phonemic():
    """REGRESSION GUARD.

    NFKD splits 'が' into 'か' + U+3099. The previous normaliser dropped every combining
    mark, so 'が' and 'か' compared EQUAL -- two different Japanese words treated as one.
    `read/duplicates.py` carried this as a known limitation; it now also backs search,
    where an over-eager fold is a wrong result rather than only a wrong dedupe verdict.
    """
    assert normalize_title("がか") != normalize_title("かか")
    assert normalize_title("ぱ") != normalize_title("は")


def test_punctuation_and_case_and_whitespace_are_flattened():
    assert normalize_title("  The   QUICK: brown-fox!  ") == "the quick brown fox"


def test_empty_input_is_empty_not_an_error():
    assert normalize_title("") == ""
    assert normalize_title("   ") == ""


def test_surname_of_handles_both_creator_shapes():
    assert surname_of({"lastName": "Welling"}) == "welling"
    # An organisation in single-field mode has no surname as such.
    assert surname_of({"name": "OpenAI, Inc."}) == "openai"
    assert surname_of({}) == ""


# --------------------------------------------------------------------------
# scoring
# --------------------------------------------------------------------------


def test_an_exact_match_scores_one():
    assert fuzzy_score(TARGET, TARGET) == 1.0


def test_case_and_punctuation_do_not_reduce_the_score():
    assert fuzzy_score("BAYESIAN, learning!", "bayesian learning") == 1.0


def test_a_substring_scores_high_but_never_beats_an_exact_match():
    """"learning" is inside "machine learning" and must not outrank the exact title."""
    partial = fuzzy_score("learning", "machine learning")
    exact = fuzzy_score("machine learning", "machine learning")
    assert 0.9 < partial < exact == 1.0


def test_the_two_typo_query_that_zotero_returns_nothing_for():
    """THE case this whole feature exists for. Zotero's search is substring-only and
    returns ZERO for this query against a paper that is definitely in the library."""
    score = fuzzy_score("Langevan Dynmaics", TARGET)
    assert score == pytest.approx(0.875, abs=0.01)
    assert score >= DEFAULT_FUZZY_THRESHOLD


def test_token_wise_scoring_beats_whole_string_scoring_on_that_case():
    """WHY the algorithm is token-wise, asserted rather than claimed in a comment.

    A whole-string ratio is dominated by length: the candidate is three times longer than
    the query, so it scores 0.395 even though every query word matches a candidate word
    almost exactly.
    """
    whole = difflib.SequenceMatcher(
        None, normalize_title("Langevan Dynmaics"), normalize_title(TARGET)
    ).ratio()
    assert whole == pytest.approx(0.395, abs=0.02)
    assert whole < DEFAULT_FUZZY_THRESHOLD < fuzzy_score("Langevan Dynmaics", TARGET)


@pytest.mark.parametrize(
    "unrelated",
    [
        "How Secure is Code Generated by ChatGPT?",
        "Ageing and Depopulation in Japan",
        "World Model for Robot Learning: A Comprehensive Survey",
    ],
)
def test_unrelated_titles_stay_below_the_threshold(unrelated):
    """The threshold is only meaningful if noise sits under it."""
    assert fuzzy_score("Langevan Dynmaics", unrelated) < DEFAULT_FUZZY_THRESHOLD


def test_a_phrase_shortcut_does_not_fire_across_word_boundaries():
    """REGRESSION. Found by an end-to-end run against the live library, not by review.

    The shortcut was a plain `" ".join(query) in candidate`, which is character-level and
    therefore matches across word boundaries: searching for "ZZ Test" scored 0.97 against
    "...Static Analysis and Fuzz Testing", because "zz test" really is a substring of
    "fuzz testing". It looks obviously correct until you watch it hit.
    """
    haystack = "Static Analysis and Fuzz Testing"
    assert fuzzy_score("ZZ Test", haystack) < DEFAULT_FUZZY_THRESHOLD
    # ...while the phrase that is genuinely there still shortcuts
    assert fuzzy_score("fuzz testing", haystack) > 0.9


def test_the_phrase_shortcut_still_fires_on_a_real_run_of_words():
    assert fuzzy_score("stochastic gradient", TARGET) > 0.9
    assert fuzzy_score("gradient langevin", TARGET) > 0.9


def test_word_order_does_not_matter():
    assert fuzzy_score("Dynamics Langevin", "Langevin Dynamics") == 1.0


def test_empty_operands_score_zero_rather_than_dividing_by_zero():
    assert fuzzy_score("", TARGET) == 0.0
    assert fuzzy_score(TARGET, "") == 0.0
    assert fuzzy_score("", "") == 0.0


def test_scores_are_bounded():
    for query in ("x", "Langevan Dynmaics", TARGET, "!!!"):
        assert 0.0 <= fuzzy_score(query, TARGET) <= 1.0
